# Generated by Django 4.1 on 2022-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
