# Generated by Django 4.1 on 2022-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_projectmodel_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
