# Generated by Django 4.1 on 2022-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_remove_taskmodel_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
