# Generated by Django 4.1 on 2022-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_projectmodel_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[('', '')], default='Complete', max_length=10),
        ),
    ]
