# Generated by Django 4.1 on 2022-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0014_remove_taskmodel_budget_remove_taskmodel_ispending'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
