# Generated by Django 4.1 on 2022-09-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0016_alter_taskmodel_budget_alter_taskmodel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[('', ''), ('AI', 'AI')], default='', max_length=10),
        ),
    ]
