# Generated by Django 4.1 on 2022-09-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_alter_taskmodel_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='task',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[('', ''), ('AI', 'AI'), ('ji', 'ji'), ('Webapp', 'Webapp'), ('kpo', 'kpo'), ('hghl;', 'hghl;')], default='', max_length=10),
        ),
    ]
