# Generated by Django 4.1 on 2022-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_remove_taskmodel_task_alter_taskmodel_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
