# Generated by Django 4.1 on 2022-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_taskmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(choices=[('ji', 'ji')], default='', max_length=10),
        ),
    ]
