# Generated by Django 4.1 on 2022-09-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0020_alter_taskmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='projects',
            field=models.CharField(max_length=10),
        ),
    ]
