# Generated by Django 4.1 on 2022-09-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0022_remove_taskmodel_projects_taskmodel_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='projects',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskapp.projectmodel'),
        ),
    ]
