# Generated by Django 4.1 on 2022-09-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0023_remove_taskmodel_projects_taskmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
