# Generated by Django 4.1 on 2022-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0028_alter_taskmodel_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
