# Generated by Django 4.1 on 2022-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0031_alter_taskmodel_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='assignee',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='personel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
