# Generated by Django 4.1 on 2022-09-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0032_remove_taskmodel_assignee_taskmodel_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
