# Generated by Django 4.1 on 2022-09-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0033_taskmodel_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='personel',
        ),
    ]
